### ISSUE TITLE
JMeterLibException: 'Incorrect log file format'

### ISSUE THREAD

**Issue by banrieen** [kowalpy/Robot-Framework-JMeter-Library#1]
When use Analyse Jtl Convert To Html    ${logpath}  after  Run Jmeter or 
directly use Run Jmeter Analyse Jtl Convert or  Run Jmeter Analyse Jtl Convert To Html get a error:
JMeterLibException: 'Incorrect log file format'
The testcases step is:

    run jmeter    ${jmeterPath}   ${scriptFile}    ${resultFile}
    Wait Until Keyword Succeeds    30    2s    File Should Exist    ${resultFile}
    ${html} =    Analyse Jtl Convert To Html    ${resultFile}

The packages info:
Jmeter  (3.2 r1790748)
robotframework (3.0.2)
robotframework-jmeterlibrary (1.1)
python (2.7.12)

**Comment by kowalpy** [comment]
Has JMeter log format changed recently? Could you please attach example log generated by current JMeter version?

**Comment by banrieen** [comment]
Ok，I have checked Jmater log, is is not the xml or csv format.

**Comment by kowalpy** [comment]
By default JMeter 3.2 generates comma separated file but format changed. I got the same error. I also found out that since JMeter 3.0 there is HTML dashboard functionality, I am not sure if supporting this library in this form still makes sense.

**Comment by kowalpy** [comment]
[I started general discussion how should version 1.2 look like (or even should it be released)](https://github.com/kowalpy/Robot-Framework-JMeter-Library/issues/2 ). Please contribute

**Comment by banrieen** [comment]
OK，thank you.

**Comment by kowalpy** [comment]
XML log is the same. CSV log differs.

**Comment by kowalpy** [comment]
@banrieen  It is fixed already in this commit: https://github.com/kowalpy/Robot-Framework-JMeter-Library/commit/d3cdd3e6622b31e92a9054c88f22e1b6e5f35f87  but not released to pypi yet. I'll release it soon.

**Comment by kowalpy** [comment]
Done. Fix available in robotframework-jmeterlibrary 1.2

**Comment by sadhananda** [comment]
Is this resolved i am still facing same issue in obotframework-jmeterlibrary 1.2

**Comment by soalexan** [comment]
I am facing the same issue JMeterLibException: 'Incorrect log file format'
Jmeter 2.12
Python 2.7.18

${logPath}= set variable    C:/Tests/output1.log    
run jmeter  C:/Tests/apache-jmeter-5.4.1/bin/jmeter.bat C:/Tests/100users.jmx   ${logPath}
${result}   analyse jtl convert ${logPath}  
log ${result}       
FOR ${ELEMENT}  IN  @{result}
log dictionary  ${ELEMENT}  

can anyone help me how to solve this?

**Comment by sadhananda** [comment]
> I am facing the same issue JMeterLibException: 'Incorrect log file format'
> Jmeter 2.12
> Python 2.7.18
> 
> ${logPath}= set variable C:/Tests/output1.log
> run jmeter C:/Tests/apache-jmeter-5.4.1/bin/jmeter.bat C:/Tests/100users.jmx ${logPath}
> ${result} analyse jtl convert ${logPath}
> log ${result}
> FOR ${ELEMENT} IN @{result}
> log dictionary ${ELEMENT}
> 
> can anyone help me how to solve this?

please share the log file file

**Comment by soalexan** [comment]
Thanks i got the issue,
I was downloaded the JmeterLib.Py and place it in python/.../site-packages which cause this problem,
now i tried to install using pip command then its working
